# -*- coding: utf-8 -*-
"""yolo_inference.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1psaai1NgFpkMlgsd9NFXvNcgyG2zJ3t6
"""

import torch
#!pip install ultralytics

model = torch.hub.load('ultralytics/yolov5','yolov5s', pretrained=True)

imgs = ['https://ultralytics.com/images/zidane.jpg']

# Inference
results = model(imgs)

# Results
results.print()
results.save()

results.xyxy[0] # img1 predictions (tensor)
results.pandas().xyxy[0] # img1 predictions (pandas)



results.show()

newimg = 'gowtham_yolo.jpg'

results = model(newimg)

results.print()

results.show()

newimg2 = 'gowtham_yolo2.jpg'
results= model(newimg2)
results.show()

newimg3 = "gowtham_yolo3.jpg"
results = model(newimg3)
results.show()

